settingsPath = r"C:\Users\HP\AppData\Roaming\.minecraft\options.txt"
MainSetting = open(settingsPath, "w")
MainSetting.truncate()
Info = []
Words = str("""version:2230
autoJump:true
autoSuggestions:true
chatColors:true
chatLinks:true
chatLinksPrompt:true
enableVsync:true
entityShadows:true
forceUnicodeFont:false
discrete_mouse_scroll:false
invertYMouse:true
realmsNotifications:true
reducedDebugInfo:false
snooperEnabled:true
showSubtitles:true
touchscreen:true
fullscreen:false
bobView:false
toggleCrouch:true
toggleSprint:true
mouseSensitivity:0.999999999999999
fov:0.0
gamma:1.0
renderDistance:2
guiScale:0
particles:2
maxFps:5
difficulty:2
fancyGraphics:false
ao:2
biomeBlendRadius:2
renderClouds:fast
resourcePacks:[]
incompatibleResourcePacks:[]
lastServer:
lang:en_us
chatVisibility:0
chatOpacity:1.0
textBackgroundOpacity:0.5
backgroundForChatOnly:true
hideServerAddress:false
advancedItemTooltips:false
pauseOnLostFocus:true
overrideWidth:0
overrideHeight:0
heldItemTooltips:true
chatHeightFocused:1.0
chatHeightUnfocused:0.44366195797920227
chatScale:1.0
chatWidth:1.0
mipmapLevels:4
useNativeTransport:true
mainHand:right
attackIndicator:1
narrator:0
tutorialStep:none
mouseWheelSensitivity:1.0
rawMouseInput:true
glDebugVerbosity:1
skipMultiplayerWarning:true
key_key.attack:key.keyboard.unknown
key_key.use:key.keyboard.unknown
key_key.forward:key.keyboard.unknown
key_key.left:key.keyboard.unknown
key_key.back:key.keyboard.unknown
key_key.right:key.keyboard.unknown
key_key.jump:key.keyboard.unknown
key_key.sneak:key.keyboard.unknown
key_key.sprint:key.keyboard.unknown
key_key.drop:key.keyboard.unknown
key_key.inventory:key.keyboard.unknown
key_key.chat:key.keyboard.unknown
key_key.playerlist:key.keyboard.unknown
key_key.pickItem:key.keyboard.unknown
key_key.command:key.keyboard.unknown
key_key.screenshot:key.keyboard.unknown
key_key.togglePerspective:key.keyboard.unknown
key_key.smoothCamera:key.keyboard.unknown
key_key.fullscreen:key.keyboard.unknown
key_key.spectatorOutlines:key.keyboard.unknown
key_key.swapHands:key.keyboard.unknown
key_key.saveToolbarActivator:key.keyboard.unknown
key_key.loadToolbarActivator:key.keyboard.unknown
key_key.advancements:key.keyboard.unknown
key_key.hotbar.1:key.keyboard.unknown
key_key.hotbar.2:key.keyboard.unknown
key_key.hotbar.3:key.keyboard.unknown
key_key.hotbar.4:key.keyboard.unknown
key_key.hotbar.5:key.keyboard.unknown
key_key.hotbar.6:key.keyboard.unknown
key_key.hotbar.7:key.keyboard.unknown
key_key.hotbar.8:key.keyboard.unknown
key_key.hotbar.9:key.keyboard.unknown
soundCategory_master:0.0
soundCategory_music:1.0
soundCategory_record:1.0
soundCategory_weather:1.0
soundCategory_block:1.0
soundCategory_hostile:1.0
soundCategory_neutral:1.0
soundCategory_player:1.0
soundCategory_ambient:1.0
soundCategory_voice:1.0
modelPart_cape:true
modelPart_jacket:true
modelPart_left_sleeve:true
modelPart_right_sleeve:true
modelPart_left_pants_leg:true
modelPart_right_pants_leg:true
modelPart_hat:true""")
List = Words.split("\n")
for phrases in List:
    MainSetting.writelines(phrases)
    MainSetting.writelines("\n")
print(List)
MainSetting.close()
